fieldLayouts:
  1641f902-613a-499c-ae3a-f3db23590dcd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2a9fc2f5-6110-436c-be30-e7ca8076a4c4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5225a655-7b1b-4da7-8cb4-690fc30967cd # Test Field
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95bdb63a-36a4-4f85-89c5-d157a9a9377a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2599de40-9db9-4cd0-a998-b8dc92ac1ce0
        userCondition: null
handle: testPage
hasTitleField: false
name: 'Test Page'
section: a4ac5263-3c77-4687-8fd9-690347916188 # Test Page
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
